// Mirrors packages/core/src/agent/boundary.ts, types.ts, inspect.ts and
// packages/web/src/input-snapshot.ts, prompt-view.ts, intent-gate.ts.
// These structural shapes keep the mod buildable against npm core 1.18.0.
export interface InputToken { readonly epoch: number; readonly revision: number }
export interface ItemView { readonly handle: number; readonly label: string; readonly number: number; readonly inscription: string | null; readonly kindId?: string; readonly tval: number; readonly sval: number; readonly artifact: boolean; readonly ego: boolean }
export interface CoreSnapshot { readonly inventory: readonly ItemView[] | null; readonly equipment: readonly (ItemView | null)[] | null }
export type ItemPrompt = { readonly kind: "item"; readonly promptId: number; readonly label: string; readonly choices: readonly { readonly handle: number; readonly label: string; readonly letter: string }[]; readonly tabs: Readonly<{ floor: boolean; quiver: boolean; equipment: boolean }> };
export type QuantityPrompt = { readonly kind: "quantity"; readonly promptId: number; readonly label: string; readonly min: number; readonly max: number; readonly defaultValue: number };
export interface InputSnapshot { readonly token: InputToken; readonly phase: "pregame" | "play" | "store" | "more" | "modal" | "dead" | null; readonly prompt: ItemPrompt | QuantityPrompt | { readonly kind: string; readonly promptId: number; readonly label: string } | null; readonly core: CoreSnapshot }
export interface InspectResult { readonly token: InputToken; readonly title: string; readonly text: string }
export interface ItemTesterResult { readonly token: InputToken; readonly items: readonly ({ readonly handle: number } | { readonly floor: { readonly x: number; readonly y: number; readonly index: number } })[] }
export interface InspectSeam { inspectItem(ref: number): InspectResult | null; itemTester(code: string): ItemTesterResult | null; itemRules?: { list(): readonly { readonly id: string; readonly label: string; readonly kind: "ignore" | "auto-inscribe" }[]; remove(id: string): { accepted: boolean; reason?: string } } }
export interface AgentCommand { readonly code: string; readonly dir?: number; readonly args?: Readonly<Record<string, unknown>> }
export interface IntentSeam { submit(token: InputToken, intent: { readonly kind: "command"; readonly command: AgentCommand }): { readonly accepted: boolean; readonly reason?: string } }
export interface PromptSeam { reply(promptId: number, answer: number): { readonly accepted: boolean; readonly reason?: string } }
export interface LoadoutStats { readonly speed: number; readonly ac: number; readonly toH: number; readonly toD: number; readonly blows: number; readonly shots: number; readonly maxHp: number; readonly maxSp: number; readonly totalWeight: number; readonly statUse: readonly number[]; readonly resists: readonly number[]; readonly resistElements: readonly string[]; readonly objectFlags: readonly string[] }
export interface LoadoutSimulation { readonly before: { readonly stats: LoadoutStats }; readonly after: { readonly stats: LoadoutStats }; readonly placements: readonly { readonly slot: number; readonly displaced: ItemView | null }[]; readonly unresolved: readonly unknown[] }
export interface ActionBuilders { wear(handle: number): AgentCommand; takeoff(handle: number): AgentCommand; drop(handle: number, quantity?: number): AgentCommand; raw(code: string, args?: Record<string, unknown>): AgentCommand }
// Mirrors packages/web/src/mod-plugin.ts ModUi and packages/core/src/agent/types.ts AgentView.
export interface ItemsContext { readonly flags?: Readonly<Record<string, boolean>>; readonly snapshot?: () => InputSnapshot | null; readonly inspect?: InspectSeam; readonly intent?: IntentSeam; readonly prompt?: PromptSeam; readonly ui?: { openPanel(spec: { id: string; modal: boolean; label: string }): { readonly root: ShadowRoot; readonly closed: Promise<void>; close(): void } }; readonly core?: { createAgentView?(state: unknown): { simulateLoadout?(change: { wield: readonly { from: "gear"; handle: number }[] }): LoadoutSimulation | null }; createAgentActions?(state: unknown): ActionBuilders }; readonly state?: unknown; readonly prefs?: { get(): unknown }; readonly log: (message: string) => void }
